### ISSUE TITLE
Use systemjs-builder?

### ISSUE THREAD

**Issue by hgl** [rolaveric/karma-systemjs#11]
Currently karma-systemjs uses systemjs and compile files on the fly in browsers. I wonder if it makes sense to use https://github.com/systemjs/builder instead? Which will bundle the test script and run the bundled code in browsers, much like how karma-browserify works.

The karma config will probably look something like this:

```js
module.exports = function(config) {
  preprocessors: [
    'test/*.js': ['systemjs']
  ],
  systemjs: {
     configFile: 'config.js' // if omitted, this is the default value
  }
};
```

And that's it. karma-systemjs will leverage systemjs builder to compile the test files into self-contained bundled code.

It should have the following benefits:

- Easier to specify the files in the conf file. Users only need to specify which test files to include, no need to make app code available to karma server.
- Slightly faster. Since browsers won't need to request all imported module and compile them, which are done in one step when karma is started.
- Less config options. No need to explicitly tell karma which transpiler to use, only where the systemjs config file is.

Not sure if you are interested in this direction.

**Comment by rolaveric** [comment]
Couldn't hurt to give it a shot and see how it goes.
It might also remove the pain from dealing with Karma's web server (ie. The whole prefixing the baseURL with '/base/' stuff).

Only thing is how to start the tests.  In a normal app, you have a single "main" module that you call, so you just set that as the self-executing module in systemjs-builder, and away you go.
Would devs need to do the same thing with tests?

**Comment by hgl** [comment]
> Would devs need to do the same thing with tests?

IMO, every test file should be treated as an entry point (i.e., the main module you mentioned). The good news is that systemjs builder support bundling multiple entry points. [jspm uses this features](https://github.com/jspm/jspm-cli/blob/master/cli.js#L384).

So karma-systemjs could pass all files users specified (that should be preprocessed by systemjs) to systemjs builder as entry points. And the final bundled code will execute these files one by one.

**Comment by rolaveric** [comment]
There's 2 main challenges I've run into so far:

1. Bundling all the test files together at once.
I can create 1 bundle per test file as the preprocessor runs over each, but there's no built in hooks in Karma to let you run something once all the preprocessors have finished.
I could copy what karma-browserify has done, but it's convoluted as hell.  It involves creating a second preprocessor to run once the first has finished to generate the single bundle file.
The tricky part of that equation is the "once the first has finished" part - making sure the bundle file is accessed last.

2. Handling 'autoWatch' mode.
With the proposed config, the only files being watched are the test files.
We need a way to either add all the dependencies from each test to the list of files that Karma watches, or create our own watchers - which is what karma-browserify does using [watchify](https://github.com/substack/watchify).

These are solvable problems, but it's going to take me some time to work on it.

**Comment by hgl** [comment]
Firstly, thank you for your efforts to implement this. :)

> Bundling all the test files together at once.

I guess we can create 1 bundle per test file as you said. Systemjs builder supports bundling a file without including the runtime code (es6 helper code, es6 polyfill code, etc). I know this because jspm supports a `no-runtime` option when bundling files. We can then serve the multiple bundled files to the server, along with the runtime code as an extra file. 

> Handling 'autoWatch' mode.

Ideally, systemjs builder should provides a list of dependencies when an entry point is bundled, that way we can add that list to the watched files (is it as simple as adding to `config.files`?)

Maybe @guybedford can offer a little help? Can systemjs builder output a list of dependencies like https://github.com/substack/module-deps does?

**Comment by guybedford** [comment]
You can use the builder API here in jspm to get a trace - 

```javascript
var builder = new require('systemjs-builder')();
builder.trace('test/*').then(function(tree) {
  // tree contains keys for all modules in the tree
  // tree can also be built directly:
  return builder.buildTree(tree, 'outfile.js');
});
```

Watchman is a good watcher I'd recommend (https://facebook.github.io/watchman/)

It might even be quite nice to do this work as a separate project (systemjs-watcher or something), and then just call into that.

**Comment by hgl** [comment]
@guybedford Thanks for the heads up.

If I'm not wrong, karma already uses chokidar for watching, and if we can get the list of dependencies, it should be as simple as add the list to the watching file list if I'm not too naive.

But I agree a separate systemjs watcher is pretty nice to have.

**Comment by rolaveric** [comment]
Thanks all.  This gives me plenty of stuff to go on.
Now I just need some spare time :)

**Comment by guybedford** [comment]
@rolaveric yes it is quite a bit to consider, no pressure! Thanks for your amazing work on this project.

**Comment by hgl** [comment]
@rolaveric Really appreciate your efforts.

However, I do realize the downsize of bundling each test file individually just now. The common dependencies of these files are now repeated:

bar.js
```js
import "foo"

assert.ok(true);
```

baz.js
```js
import "foo"

assert.ok(false);
```

Bundling the two files individually is going to serve two copies of `foo` to the browser.

But since the files are served locally, I guess it's an acceptable trade off?

**Comment by rolaveric** [comment]
Acceptable for a first version at least.
Get the systemjs-builder process and watchers going first, then worry about bundling everything in one hit.
If the performance degrades in the meantime, well... that's what semver ranges and branches are for :)

**Comment by hgl** [comment]
:+1: , sounds like a plan. :)

**Comment by rolaveric** [comment]
Got some progress 45d5c23e8ccea7d180aebb09307925b16b18dab9
I made use of the arithmetic features in systemjs-builder so that each subsequent test suite is bundled without anything from the previous test suites.
It's not as fast as doing everything in one hit, but it's better than the errors I was getting when 2 bundles tried to run their own copies of Angular.

I've got an example of it running on the angular-phonecat tutorial:
https://github.com/rolaveric/angular-phonecat/commit/88244d2bb0dc5b244d91136f14d0133b090d7db5
You can see how much simpler the karma.conf.js becomes.

Next step will be getting the watchers going.

**Comment by hgl** [comment]
Thank you! Looks great. Will check it out tonight.

**Comment by hgl** [comment]
Just tried it but encountered a few hiccups: 

It should use user's system config.js file, which also contains package dependencies info. Currently it doesn't recognize any of my dependencies.

`systemjs-builder` should be listed under `dependencies ` in package.json. Otherwise after installing karma-systemjs, starting karma complains that it can't find it. I'm not sure if `es6-module-loader` and `systemjs` are still needed.

**Comment by rolaveric** [comment]
_It should use user's system config.js file_

It does though.
You specify where the user's `system.config.js` is under `systemjs.configFile` in the karma config, which is then added to the list of files that karma includes:
https://github.com/rolaveric/karma-systemjs/blob/builder/lib/framework.js#L83
The config specified at `systemjs.config` in the karma config is entirely optional - a convenience for things like adding modules for testing or changing the `baseURL`, if you needed to.

`karma-systemjs` needs to know what the config is so that it can get the `baseURL`, and use it to map file paths (eg. `/home/rolaveric/WebStormProjects/angular-phonecat/test/unit/controllerSpec.js`) to module names (`test/unit/controllerSpec`).
It also needs to pass the config onto `systemjs-builder`.

_`systemjs-builder` should be listed under `dependencies` in package.json_

Good point.
I've been reluctant to specify dependencies where I can get away with it because I'm afraid I won't notice that a new version has been released, and suddenly people are using SystemJS v0.20.0 in their apps while karma-systemjs tests using v0.16.0.
But I suppose that's no excuse.

_I'm not sure if `es6-module-loader` and `systemjs` are still needed._

You're right about `es6-module-loader`, but I think `systemjs` is still required because `karma-systemjs` still needs to call `System.import(testSuiteModuleName)`.
Unless `systemjs-builder` already includes `System.import()` in bundles.
If I can get everything included in a single bundle, I can make that bundle self-executing, meaning `System.import()` isn't required.

**Comment by hgl** [comment]
> It does though.

Ah, sorry for missing it.

Currently the preprocess reads `config.systemjs.config` directly, this can fail if user didn't define `systemjs` in the karma config file, and they get a cryptic `Can not load "systemjs"!` error.

> suddenly people are using SystemJS v0.20.0

You can lock the version down by simply specifying the version (with nothing prefixed) in package.json.

> Unless systemjs-builder already includes System.import() in bundles.

I believe `builder.buildSFX` does.

**Comment by rolaveric** [comment]
_they get a cryptic error_

Well spotted.  I'll add some checks to make sure the user includes either a `config.systemjs.configFile` or a `config.systemjs.config` (_maybe_ they want to completely override the config...), and raise an error if they're not.

_I believe builder.buildSFX does._

Trouble there is `build.SFX()` won't let you use this `testSuite2 - testSuite1` as the module expression.  It'll let you add, but not subtract.
So I need to get the "all in one bundle" process going.

**Comment by rolaveric** [comment]
I just found [karma-jspm](https://github.com/Workiva/karma-jspm).
It seems to work in a similar fashion to `karma-systemjs` (eg. Serve but not include each file and use System.import() to load them), except that it makes use of the JSPM structure.
eg. Looks in `package.json` to find the SystemJS config file (default to `config.js`) and packages folder (default to `jspm_packages/`).

Another caveat with the bundles approach is that it's not possible (or at least not practical) to use other preprocessors.  eg. `karma-coverage`
Combine that with custom watchers and the hoop jumping required to get everything in a single bundle, I'm starting to question if this is worth the trouble.
So far the only thing we're gaining, from a user perspective, is only having to specify the test files in the karma config.

**Comment by hgl** [comment]
I think you have good point concerning bundling files.

But if I'm not wrong, the current master branch architecture doesn't supporting using `karma-coverage` for an imported jsx file for example?

What about we define a systemjs preprocessor, but only transpile each individual file:

```js
module.exports = function(config) {
  frameworks: ['mocha', 'systemjs'],
  files: [
    "app/*.jsx",
    "test/*.js"
  ],
  preprocessors: [
    "app/*.jsx": ['systemjs', 'coverage']
  ]
};
```

Making this plugin works much like [karma-commonjs](https://github.com/karma-runner/karma-commonjs)

Not totally sure, but does it work like this: transpile each file using es6-module-loader and serve them along with systemjs to the browser?

**Comment by guybedford** [comment]
Transpiling files individually into System.register is the most efficient workflow.

I've created https://github.com/systemjs/builder/issues/126 if it would make this easier.

For now this can be done for ES6 only though via Babel or Traceur directly.

**Comment by hgl** [comment]
Thank you @guybedford, if systemjs builder can directly support it, it will make things much easier.

**Comment by rolaveric** [comment]
Good idea.
Ideally we'd want to run coverage first, so the reports show the source code.
But with ES6 coverage support still sketchy, and the plethora of "compile down to Javascript" languages out there, that's not really practical.

**Comment by hgl** [comment]
Systemjs builder should be able to generate an inline source map, and hopefully coverage will pick it up and generate a new one accordingly.

**Comment by rolaveric** [comment]
I'm going to close this issue off as stale.
I don't think the possible benefits would outweigh the complexities.
