### ISSUE TITLE
Trying to get bootstrapped...bit confused!

### ISSUE THREAD

**Issue by dmackerman** [rolaveric/karma-systemjs#12]
I'm very new to all the ES6 / SystemJS / JSPM world, so excuse my ignorance. We've got an Angular project working with System and JSPM with Babel. Everything works pretty well, and now we're trying to get our unit tests running again. I tried to follow the README in addition to the sample projects out there, but I seem to be falling short...

Here's my `karma.config`:

```js
module.exports = function(config) {
    config.set({
        singleRun: false,
        colors: true,
        plugins: ['karma-jasmine', 'karma-phantomjs-launcher', 'karma-systemjs'],
        frameworks: ['jasmine', 'systemjs'],
        browsers: ['PhantomJS'],
        reporters: ['dots'],

        systemjs: {
            // Path to your SystemJS configuration file
            configFile: 'src/app/system.config.js',

            // File patterns for your application code, dependencies, and test suites
            files: [
                'src/app/**/*.js',
                'test/unit/**/*.spec.js'
            ],

            // SystemJS configuration specifically for tests, added after your config file.
            // Good for adding test libraries and mock modules
            config: {
                transpiler: 'babel',
                paths: {
                    'angular-mocks': 'jspm_packages/github/angular/bower-angular-mocks@1.3.15/angular-mocks.js'
                }
            },

            // Specify the suffix used for test suite file names.  Defaults to .test.js, .spec.js, _test.js, and _spec.js
            testFileSuffix: '.spec.js'
        }

    });
};
```

1. Is the way we're loading 'angular-mocks' correct? The path is right, so I don't see why it wouldn't work.

2. It was my impression that defining the `configFile` would load all of my dependencies, is that not correct? I've removed all of my tests and and currently just trying to get one test to execute:

**test/unit/app.spec.js**
```js
'use strict';

import 'angular';
import 'angular-mocks';

describe('KickstartApp', function() {

    beforeEach(angular.mock.module('kickstartapp'));

    it("should run a dummy test", function() {
        expect(1 + 1).toBe(2);
    });

});
```

When I run Karma, I get this error:

```
PhantomJS 1.9.8 (Mac OS X) ERROR
TypeError: Illegal module name "/test/unit/app.spec"
PhantomJS 1.9.8 (Mac OS X): Executed 0 of 0 ERROR (0.169 secs / 0 secs)
INFO [watcher]: Changed file "/Users/dave/Sites/kickstart-app/client/test/unit/app.spec.js".
```

If I open up the debug window in Karma, I get this error:
![error](https://dl.dropboxusercontent.com/spa/pkr1d5uhq1t8wz1/r5gjwekg.png)

What am I doing wrong? Thanks!

**Comment by rolaveric** [comment]
1. Yep, that looks correct to me.
2. Defining `configFile` means it gets loaded into `systemjs` on the browser, and `karma-systemjs` uses it to work out what transpiler to load.  The `systemjs.files` are what gets loaded.

Odd thing is, just from eyeballing it, I can't see anything you're doing wrong.
It doesn't like the module name because it starts with a '/' - but `karma-systemjs` should handle stripping that out.
What version of Karma are you using?

**Comment by dmackerman** [comment]
Using `0.12.17` right now.

**Comment by rolaveric** [comment]
Hmmm, that's weird.  I can't seem to replicate your error.
I'm using the latest karma (0.12.31), but I doubt that's the issue.

Any chance you can create a github repo that replicates it?

**Comment by rolaveric** [comment]
Hi @dmackerman 
Is this issue still occurring for you?

**Comment by rolaveric** [comment]
Closing issue as stale.
