### ISSUE TITLE
WARN [web-server]: 404: /base/babel.js with babel 5.1.10

### ISSUE THREAD

**Issue by ldeavila** [rolaveric/karma-systemjs#17]
Caused by incorrect relative path in index.js, line 105

`getDependencyPath('babel', '/../../../browser.js') :`

Fixed by setting relative path to '/node_modules/babel-core/browser.js'

**Comment by cmlizama** [comment]
I found a similar issue with the relative path to the es6module loader depedency. Also fixed by changing the path.

**Comment by ldeavila** [comment]
I could see this issue easily reappearing. Maybe make the karma-systemjs module dependent on a specific version of babel, traceur, and es6module? Or add a parameter to the systemjs config object?

**Comment by rolaveric** [comment]
Making the dependency paths configurable sounds like the best option.

**Comment by ldeavila** [comment]
Let me see if I get some time to work on it. Maybe next week.

**Comment by mntnoe** [comment]
It would be nice if not only the parameter to getDependencyPath() was configurable, but all the dependencies could be overriden. Perhaps an option in karma.conf.js containing an array of paths to prepend to the files array, which if given would replace the default approach of resolving es6-modules, systemjs etc from node_modules. This would allow bower users to use the versions given in their bower config.
