### ISSUE TITLE
FEATURE: Support config options for traceur, babel, and systemjs

### ISSUE THREAD

**Issue by ldeavila** [rolaveric/karma-systemjs#18]
Use Case: Been playing around with Angular2 and the Angular2 demo app which happens to use annotations. Wanted to setup some Karma tests for it. Annotations support is not enabled by default for traceur. Here is how you can do it.

Edit adapter.js and add the following

  // Hack for setting traceur and system options to support experimental stuff, like annotations
  `System.traceurOptions = traceur.util.Options.experimental(); // the whole kitchen sink`
  `System.traceurOptions = { annotations : true }; // just annotations`

This is of course a total hack. 

Feature wise it might make sense to add config params to the systemjs propery in karma.conf

**Comment by rolaveric** [comment]
You should be able to set your `System.traceurOptions` in your SystemJS config file.
If your SystemJS config is (for some reason) different during testing, you can add the config to "systemjs.config" inside your karma config - same way you can set additional paths.

**Comment by ldeavila** [comment]
Perfect. It works. Thanks for the tip.
