### ISSUE TITLE
Deprecate use of 'require.resolve()'

### ISSUE THREAD

**Issue by rolaveric** [rolaveric/karma-systemjs#24]
Originally dependency paths were included in the `files` array by looking them up using `require.resolve()`.
Problem with that method is that if the location of the file you're looking up changes, the plugin breaks.  It also doesn't work if those dependencies are loaded by something other than npm (eg. jspm, bower, or manually).

So an alternative method was added where dependencies could be specified in the SystemJS config, as they likely had to be anyway. eg:
```js
System.config({
    paths: {
        babel: 'node_modules/babel-core/browser.js'
    }
});
```

The former method should now be deprecated, with warnings logged stating that the paths should be added to the SystemJS config.

**Comment by msegado** [comment]
Might be good to update the readme to reflect this, and perhaps include an example config that people using npm can easily copy-paste to get up and running; e.g.,

```js
paths: {
  'babel': 'node_modules/babel-core/browser.js',
  'systemjs': 'node_modules/systemjs/dist/system.js',
  'system-polyfills': 'node_modules/systemjs/dist/system-polyfills.js',
  'es6-module-loader': 'node_modules/es6-module-loader/dist/es6-module-loader.js',
  'phantomjs-polyfill': 'node_modules/phantomjs-polyfill/bind-polyfill.js'
}
```

**Comment by rolaveric** [comment]
Good idea - I'll update the config sample to include the other modules.
