### ISSUE TITLE
Missing TypeScript support

### ISSUE THREAD

**Issue by timkindberg** [rolaveric/karma-systemjs#25]
Howdy, I using this with SystemJS using TypeScript and I'm running into problems. I noticed you only have Traceur and Babel support.

**Comment by rolaveric** [comment]
Good point.
Since the ideal behaviour is to lookup the transpiler in the SystemJS config, it should be possible to make a generic change that will support babel, traceur, typescript, and any future options.
I'll make the changes when I get home tonight.

**Comment by timkindberg** [comment]
You da man

**Comment by rolaveric** [comment]
Fixed by 93509633a641b8d4ca399a47f49d697bdced1953

**Comment by timkindberg** [comment]
THANKS!!

**Comment by kosz** [comment]
@timkindberg @rolaveric do you guys have any examples of this. i have not been successful in setting it up so far https://github.com/kosz/jspm-ts-playground
