### ISSUE TITLE
Uncaught TypeError: baseURL should only be configured once and must be configured first

### ISSUE THREAD

**Issue by piebe** [rolaveric/karma-systemjs#27]
- karma-systemjs 0.6.0 with systemjs 1.18 
- meta information defined in System.config.

starting karma the following error is shown:

     Uncaught TypeError: baseURL should only be configured once and must be configured first.

When I do not define a baseURL, I get the following error:

     D:/project/lala/lala-core/undefined../bower_components/traceur/traceur.js

where undefined is at the location where normally the baseURL is inserted...

- Going back to systemjs 1.7 and defining baseURL solves the problem. 
- removing the meta element and defining baseURL solves the problem

But of course I want to use 1.8 and the meta element...

**Comment by rolaveric** [comment]
Thanks for the heads up.
I'll change the adapter so it makes sure the baseURL is only ever set once, and always first.
I'll also fix up uses of baseURL to handle it being undefined. eg. Use path.join() or set an appropriate default.

**Comment by rolaveric** [comment]
Should be fixed by f13fe355a85c2593ead7007a6614cf20447ed3db
Published as 0.7.0

**Comment by piebe** [comment]
thx things are working properly now.
