### ISSUE TITLE
karma-coverage

### ISSUE THREAD

**Issue by piebe** [rolaveric/karma-systemjs#29]
Is it possible to use karma-systemjs in combination with karma-coverage? Is there an example of a working configuration?

**Comment by rolaveric** [comment]
I've never tried it before, though I don't see any reason why it shouldn't work.
The preprocessor should instrument the code before SystemJS loads it, and then it just needs to hook into `karma.start()` to generate the report.
I'll give it a test now and see what I can find.

**Comment by rolaveric** [comment]
Got it working: https://github.com/rolaveric/angular-seed/commit/cb9337145d8a4873ddc9ae0486111b1b6e9427df
The trick was getting `karma-coverage` to use a different instrumenter that supports ES6.
Thankfully I found this commit: https://github.com/douglasduteil/karma-coverage/commit/626e7b0c5a36fba948f6be349020e62794a79377
However, the helpful README information that tells you how to use a different instrumenter is now missing from the master README file - that's what made this situation more confusing than it had to be.

I'm going to add a note to `karma-systemjs`'s README about how to use it with `karma-coverage`.
