### ISSUE TITLE
testFileRegex vs testFileSuffix

### ISSUE THREAD

**Issue by unional** [rolaveric/karma-systemjs#32]
Hi,

Is there any reason you do a `testFileSuffix` vs just `testFileRegex`?  I want to have more control on which tests I want to run through jake/gulp/grunt.   e.g. `jake runtests tests=componentA`

**Comment by rolaveric** [comment]
I think it's because I wanted to use globs since that's what Karma uses for all it's paths.
But wasn't sure how to do so at the time, so I took the lazy option and just used a suffix test.

A Regex would be a lot better then just a suffix test though - that's for sure.

**Comment by unional** [comment]
Saw you picked up the PR. Thanks!
