### ISSUE TITLE
How can I use this with JSPM & typescript (which i convert to ES6)

### ISSUE THREAD

**Issue by robertbaker** [rolaveric/karma-systemjs#35]

**Comment by rolaveric** [comment]
In your SystemJS Config file, make sure to specify the location of `systemjs`, `es6-module-loader`, and the browser version of your transpiler (eg. `"typescript": "node_modules/typescript/bin/typescript.js"`)

In your Karma config, add a `systemjs` property which defines:
* Path to your SystemJS config file under `configFile`
* List of file patterns you need served under `files`
* The suffix of your test files under `testFileSuffix`, or a regex under `testFileRegex`
* Any SystemJS config changes you need to make (eg. paths to test libraries, different baseURL) under `config`

If you're still having trouble, please create a github repo with the project setup you're having trouble with.
That'll give me something to debug, and work as an example for others too.

**Comment by robertbaker** [comment]
```
[09:05:26] Using gulpfile c:\git\pos\gulpfile.js
[09:05:26] Starting 'test'...
WARN [watcher]: All files matched by "c:\git\pos\.build\jspm_packages\system-polyfills.js" were excluded.
WARN [watcher]: All files matched by "c:\git\pos\.build\jspm_packages\system.js" were excluded.
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Windows 8 0.0.0)]: Connected on socket P7_mWIvfvUKdD1PBnQv8 with id 59623085
PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating 'System.config(karma.config.systemjs.config)')
  at c:/git/pos/node_modules/karma-systemjs/lib/adapter.js:87

PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.128 secs / 0 secs)
```

**Comment by rolaveric** [comment]
lib/adapter.js line 87: `System.config(karma.config.systemjs.config);`
It's finding `System` undefined.

The problem comes from lines 3 & 4 of your logs:
```
WARN [watcher]: All files matched by "c:\git\pos\.build\jspm_packages\system-polyfills.js" were excluded.
WARN [watcher]: All files matched by "c:\git\pos\.build\jspm_packages\system.js" were excluded.
```
It's not loading SystemJS, so the `System` object comes out as `undefined`.

**Comment by kosz** [comment]
@rolaveric not sure if I should open another issue or ask here, but have the same question ( just maybe that i'm stuck in a different place ). Here is the repo i'm testing things in: https://github.com/kosz/jspm-ts-playground.

**Comment by robertbaker** [comment]
Actually, I forked and merged in the PR by @omerts. Fixed my problem with
that and a few proxies. This plugin needs more fixes though, the 404s
people are getting are not just misconfiguration.

**Comment by rolaveric** [comment]
Hi @kosz 
I had a bit of trouble with your example (JSPM kept saying `Registry typescript not found` o__0) so I created a new project based off of it.
I did get it working, but it could definitely use some polishing up.  Here's the changes I made:
1. Set the transpiler to 'typescript', rather than using the '.ts!' plugin.  Requires the latest beta JSPM: 0.16.0-beta.3
2. I renamed '.ts' files to '.js'.  I could set "defaultJSExtensions" to false, but that also means changing EVERY module reference to include '.js', so I took the cowards way out (What can I say? It's 11pm and I'm tired).
3. I changed the testing framework to Jasmine - just what I'm used to.  I did have to add a pointless 'import' statement to `app.spec.js` though because without it SystemJS wasn't registering that it needed to run a transpiler over it.
4. I did a blanket import of every ".js" file in "jspm_packages" in `karma.conf.js` rather than pick out specific files.

Hopefully that helps.

**Comment by rolaveric** [comment]
And I just realised I didn't actually link to my example project :P
https://github.com/rolaveric/ts-jspm-playground

**Comment by robertbaker** [comment]
@rolaveric  I switched back to this.

my setup is now /src/**/*.ts
and /src/**/*.spec.js

my baseUrl is the default

jspm_packages is in the root, as well as my config.js

here is my karma config.

```
// Karma configuration
var gc = require('./gulp.config.json');
var path = require('path');
module.exports = function(config) {
    config.set({
        //urlRoot: '/base',
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['systemjs', 'jasmine'],
        //files: [
        //    // This is needed since SystemJS depends on Function.bind(), which is not supported in PhantomJS.
        //    'node_modules/phantomjs-polyfill/bind-polyfill.js'
        //],


        systemjs: {
            configFile: "config.js",
            baseURL: "/",
            config: {
                transpiler: null,
                "paths": {
                    "systemjs": "jspm_packages/system.js",
                    "system-polyfills": "jspm_packages/system-polyfills.js",
                    "babel": "jspm_packages/npm/babel-core@5.8.3/browser.js",
                    "typescript": "jspm_packages/github/mhegazy/typescript@v1.5-beta2/bin/typescript.js",
                    "es6-module-loader": "node_modules/es6-module-loader/dist/es6-module-loader.js",
                    "angular-mocks": "jspm_packages/github/angular/bower-angular-mocks@1.4.3/angular-mocks.js"
                }
            },
            files: [
                'src/**/*.ts',
                //'.build/app/**/*.js',
                'src/**/*.spec.js'
            ],
        },


        // jspm: {
        //     serveFiles: [
        //         './.build/app/**/*.js'],

        //     loadFiles: [
        //         'src/app/**/**.spec.js'
        //     ]
        // },
        // proxies: {
        //'/base/src/app': '/base/.build/app',
        //     // '/base/jspm_packages': '/base/.build/jspm_packages',
        //     '/base/app/src/app': '/base/src/app',
        //     '/base/app': '/base/.build/app'
        // },

        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        //'PhantomJS'
        browsers: ['Chrome',],

        preprocessors: {
            'src/**/!(*spec).js': ['babel', 'coverage']
        },

        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['coverage', 'spec'],
        coverageReporter: {
            // isparta works as a custom instrumentor, which must be registered in Karma config:
            instrumenters: {isparta: require('isparta')},
            instrumenter: {
                'src/**/*.js': 'isparta'
            },

            reporters: [
                {
                    type: 'text-summary'
                },
                {
                    type: 'html',
                    dir: gc.path.coverage,
                    subdir: '.'
                }
            ]
        },

        // list of files to exclude
        exclude: ['jspm_packages/*'],

        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO ||
        // config.LOG_DEBUG
        logLevel: config.LOG_INFO,

        // enable / disable colors in the output (reporters and logs)
        colors: true

    });
};
```

**Comment by robertbaker** [comment]
@rolaveric any idea why it's not loading systemjs

**Comment by Maks3w** [comment]
This setup works ok for me:

```js
// karma.conf.js

module.exports = function (config) {
  config.set({

    basePath: "./",

    frameworks: [
      "jasmine",
      "systemjs"
    ],

    systemjs: {
      config: {
        paths: {
          systemjs: "bower_components/system.js/dist/system.src.js",
          typescript: "node_modules/typescript/bin/typescript.js"
        },
        transpiler: "typescript"
      },

      testFileSuffix: ".spec.ts"
    },

    files: [
      {pattern: "app/**/*", served: true, included: false},
      "bower_components/angular/angular.js",
      "bower_components/angular-route/angular-route.js",
      "node_modules/angular-mocks/angular-mocks.js"
    ]
  });
};
```

```js
// package.json
{
 "dependencies": {
    "typescript": "^1.5.3"
  },
  "devDependencies": {
    "angular-mocks": "^1.4",
    "bower": "^1.4.1",
    "jasmine-core": "^2.3.4",
    "karma": "^0.13.3",
    "karma-chrome-launcher": "^0.2",
    "karma-firefox-launcher": "^0.1.6",
    "karma-jasmine": "^0.3.5",
    "karma-systemjs": "^0.7.2"
  }
}
```

```js
// bower.json
{
  "dependencies": {
    "angular": "~1.4",
    "angular-route": "~1.4",
    "system.js": "~0.18.4"
  },
}
```

```ts
///<reference path="../../../typings/tsd.d.ts"/>

import {ConfiguratorProvider} from "./ConfiguratorProvider.ts";

describe("Test", ():void => {
    it("Assertion", ():void => {
        let configurator:ConfiguratorProvider = new ConfiguratorProvider();
        expect(configurator).toEqual(true); // Force failure
    });
});
```

**Comment by Maks3w** [comment]
Note in the above setup packages `es6-module-loader` and `system-polyfills` are not installed and `systemjs` is installed as a bower package.

Setup works ok anyway /cc @rolaveric because warning messages printed while lunch should be removed

```
[WARNING] Looking up paths with require.resolve() is deprecated.
Please add "es6-module-loader" to your SystemJS config paths.
Cannot find "es6-module-loader".
  Did you forget to install it ?
  npm install es6-module-loader --save-dev
[WARNING] Looking up paths with require.resolve() is deprecated.
Please add "system-polyfills" to your SystemJS config paths.
01 08 2015 10:33:44.446:WARN [watcher]: Pattern "undefined" does not match any file.
Cannot find "systemjs".
  Did you forget to install it ?
  npm install systemjs --save-dev
01 08 2015 10:33:44.447:WARN [watcher]: Pattern "undefined" does not match any file.
```

**Comment by rolaveric** [comment]
@robertbaker  The second line shows that it's tried to load `system.js`, which is where the `System` global object comes from, but it's been excluded.
If you comment out the `exclude: ['jspm_packages/*']` line in your config you should get a better result.

@Maks3w Thanks for the example.
I think I need to review exactly when `es6-module-loader` and `system-polyfills` are required.  I suspect they may only be required if you use Babel as the transpiler, which is why everything works fine for you using Typescript.

**Comment by kosz** [comment]
@rolaveric thanks for your input. 

I have been trying for a few hours, various things, without being able to get it to work. 
I have tried using your playground project, however on jspm install I get the following error : 
```
     Installed Forks

          github:mhegazy/typescript v1.5-beta2 1.5.0-alpha

     To inspect individual package constraints, use jspm inspect registry:name.


err  TypeError: Invalid Version: v1.5-beta2
         at new SemVer (/Users/cosmin/src/rangle/temp/jspm-cli/node_modules/semver/semver.js:293:11)
         at Range.test (/Users/cosmin/src/rangle/temp/jspm-cli/node_modules/semver/semver.js:1047:15)
         at Function.satisfies (/Users/cosmin/src/rangle/temp/jspm-cli/node_modules/semver/semver.js:1096:16)
```

node 0.12.4
jspm 0.16.0-beta.3

It looks like this typescript project is a fork of the Microsoft project.

**Comment by robertbaker** [comment]
the latest jspm master uses offical 1.5.3, you can replace that with npm:typescript@1.5.3

**Comment by kosz** [comment]
@robertbaker when trying with npm:typescript@1.5.3 I get the following error : 

```
Chrome 46.0.2461 (Mac OS X 10.10.2) ERROR
  Uncaught ReferenceError: require is not defined
  at /Users/cosmin/src/rangle/src/zip.frontend/jspm_packages/npm/typescript@1.5.3/bin/typescript.js:37661
```

my current setup : 

```
System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "typescript",
  "paths": {
    "github:*": "../jspm_packages/github/*",
    "npm:*": "../jspm_packages/npm/*",
    "system-polyfills": "jspm_packages/system-polyfills.js",
    "systemjs": "jspm_packages/system.js",
    "typescript": "jspm_packages/npm/typescript@1.5.3/bin/typescript.js",
    "es6-module-loader": "node_modules/es6-module-loader/dist/es6-module-loader.js",
    "phantomjs-polyfill": "node_modules/phantomjs-polyfill/bind-polyfill.js"
  }
});
```

i've tried all variations of typescript i could think off, including the old beta package referenced above, another alpha package from that fork, and different files.

**Comment by kosz** [comment]
this same file with the require call, also gets loaded in the browser while using the app normally, but it does not throw an error then. only when running with karma it throws the require error

**Comment by kosz** [comment]
trying with alpha : 

```
Chrome 46.0.2461 (Mac OS X 10.10.2) ERROR
  Uncaught ReferenceError: module is not defined
  at /Users/cosmin/src/jspm_packages/github/mhegazy/typescript@1.5.0-alpha.js:1
```

**Comment by kosz** [comment]
@rolaveric @robertbaker some interesting info here, seems to provide a fix for my issue. 

http://blog.rangle.io/unittests/ 

Funny enough I work next to the gentleman that wrote that blog post, but we don't interact all that much. Either way, I think we're almost there to getting this figured out and within a few weeks we could do with TypeScript all the cool things that we can do with Babel/Traceur.

**Comment by robertbaker** [comment]
@rolaveric  I have created a test repo.

Hello, for the past month I been trying to get unit tests to run with either karma-jspm or karma-systemjs.

I have created a bare bones repo for you to test and help get them running.

```
npm i
jspm update
gulp tsd
gulp test
```

In the karma.config you will see 2 configurations. One for karma-jspm and one for karma-systemjs.
Please comment/uncomment the appropiate configuration.

I would really appreciate the team taking their time and trying to get them to run. I'm pulling out my har, I really need to get my units tests running again.

The repo contains 2 layouts. They differ by baseURL.

Layout 1 uses plugin-typescript, with a baseURL of "/"

Layout 2 is what I'm using in my project now. The typescript is transpiled into /.build/app
the jspm_packages and config live in .build.

The only thing I care about is to get the unit tests to run. If that means you need to rearrange things, go ahead.

The test repo:
https://github.com/robertbaker/system-unit-test

**Comment by nicklasb** [comment]
@robertbaker, @rolaveric  : I just got my tests to run using jspm, but the problem for me is that even if I set `transpiler: "typescript"` and `testFileSuffix: '.spec.ts'`, it keeps looking for *.spec.ts.js instead of .spec.ts. 

I presume that this might be related to the `defaultJSExtensions: true` i have in the original `configFile`, but I am not sure, as [I have gathered](https://github.com/rolaveric/karma-systemjs/issues/38) that karma-systemjs implements its own way of finding the test files.

**Comment by nicklasb** [comment]
If you read by email, I edited the above post.

**Comment by rolaveric** [comment]
If `defaultJSExtensions: true`, SystemJS will assume for any module, unless it runs through a plugin (eg. 'template.html!text') or has an explicit path set in the config, that it's path will be "{module name}.js".
That's why you're probably getting 404s looking for ".spec.ts.js" files - karma-systemjs has likely called `System.import('some/path/app.spec.ts')`, and SystemJS has gone ahead and tacked a ".js" to the end.

The only other thing karma-systemjs does is try to remove '.js' from the end of a file path to try and get the real module name (otherwise you end up with 404s looking for "*.js.js"), but only if `defaultJSExtensions: true` is set.  And since your file doesn't have ".js" at the end, nothing would happen.

The whole file extension thing really is a massive PITA.  Even if you set `defaultJSExtensions: false`, you still have countless third-party modules which will otherwise break.  I assume it must be possible (or will be in the near future) to apply a scope to this setting.
eg. Everything I control under `src/` has it set to false, third party modules A, B, and C are set to false, and everything else is true.

**Comment by nicklasb** [comment]
Hi, thanks for your reply, I will see how I can work around is.
Yes, the PITA certainly is massive on this one, no matter how paved with good intentions the road there was..

**Comment by rolaveric** [comment]
Well to be fair, I don't know of any other module loader that's ever had to deal with multiple languages and file extensions simultaneously.

**Comment by nicklasb** [comment]
Oh, I am not meaning to overly critical, it was just the old realisation that it is impossible to get stuff right from the start. It is good that these things where realized this early on, I think most that use SystemJS now are a bit on the bleeding edge, and hopefully aware of that. 

So at this stage, and IMO, it is far better to break some solutions and help those few out to make it right than to try and be overly incremental and backwards compatible, a balance SystemJS seems to strike well with the last releases.

**Comment by rolaveric** [comment]
Very true.

**Comment by vintem** [comment]
@Maks3w I made it work using your example, thank you. One question, is there a way not to use the extension when imporint a module. Because when I do this:

import {ConfiguratorProvider} from "./ConfiguratorProvider.ts";

My text editor will say that it cannot find the specified module. And if I remove the .ts the test will fail.

I tried with ST3, Atom and Code. Thanks

**Comment by rolaveric** [comment]
It looks like SystemJS now supports a `packages` object in it's configuration where you can set a 'defaultExtension' for a given path.
https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages
So for example you could set `defaultExtension: false` for your source code, where you can just use the real extension in your imports, but let it fallback to `defaultExtension: 'js'` for third-party modules.

**Comment by ryanwischkaemper** [comment]
Thanks for all the information in this issue - helped a lot! [Here's a repo](https://github.com/ryanwischkaemper/aurelia-typescript-tests) that has Typescript unit tests working in Karma with autowatch and everything. It uses the Typescript transpiler via SystemJS and the karma-systemjs plugin. The `wallaby.js` file is also configured and working (tested in Atom)

**Comment by kosz** [comment]
thanks for sharing @ryanwischkaemper

**Comment by rolaveric** [comment]
Nice work @ryanwischkaemper 
I've added your repo to the README as a prime example of using Typescript.
