### ISSUE TITLE
ES6 imports not working.

### ISSUE THREAD

**Issue by richburdon** [rolaveric/karma-systemjs#39]
It's not clear how to get ES6 import statements to work (e.g., via babel)

I have this in my karma.conf.js

    preprocessors: {
      'src/main/javascript/**/*.js' : ['babel']
    },

When I karma run, I get:

    PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
    ReferenceError: Can't find variable: require
    at src/main/javascript/test_sandbox.js:2

    test_sandbox.js:
    'use strict';
    import './sandbox.js'

EDIT: I added the following to the karma config:

    babelPreprocessor: {
      options: {
        modules: 'system'
      }
    }

And now get:
Uncaught TypeError: Invalid anonymous System.register module load.

**Comment by richburdon** [comment]
Working now.
"files" must be defined in "systemjs"

**Comment by hjmeric** [comment]
HI @richburdon, what did you mean "files" must be defined in "systemjs"?
I encountered the same issue. Could you give me the example? Thanks.
