### ISSUE TITLE
`karma.error`

### ISSUE THREAD

**Issue by whitneyit** [rolaveric/karma-systemjs#40]
After *incorrectly* setting up `karma-systemjs` I was receiving this error

> TypeError: karma.error is not a function

When I run the following `typeof window.__karma__.error` I get `'undefined'`.

The call to `karma.error` is being used [here](https://github.com/rolaveric/karma-systemjs/blob/f7c922457e8e244d83b12ca35a0394759df996a9/lib/adapter.js#L100) and [here](https://github.com/rolaveric/karma-systemjs/blob/f7c922457e8e244d83b12ca35a0394759df996a9/lib/adapter.js#L108).

Is there any reason for this? Can we just dump the error as is?

**Comment by rolaveric** [comment]
It's done that way because errors need to be fed into Karma so that they can in turn be fed into the reporters.
Otherwise they won't get picked up on things like JUnit reporters used by CI servers like Bamboo.

I could dump the errors out using `console.log()`, but it might get a bit noisy.
Better option might be to check that `window.__karma__` is defined first and fail fast if it's not.

**Comment by diestrin** [comment]
Hey guys. This is currently happening in my set up. I have
```
frameworks: ['systemjs', 'jspm', 'jasmine'],
plugins:[
  "karma-jspm",
  'karma-jasmine',
  'karma-chrome-launcher',
  "karma-systemjs"
],
```

What's the missing config to be able to call karma.error? It's undefined if I open the browser and try to debug on it. I tried looking at the karma source code but couldn't find that method defined anywhere.

**Comment by rolaveric** [comment]
First thing I see is you're using both `karma-jspm` and `karma-systemjs`.
You don't need both. If you're using JSPM I recommend going with `karma-jspm`.

**Comment by FredLoney** [comment]
The problem identified by diestrin, and perhaps by whitneyit, is actually a karma bug. In debug mode, the karma debug.html page load creates a limited karma object which does not include an error function. I [forked](https://github.com/ohsu-qin/karma) karma and added a debug.html error function which corrects the immediate error and allows karma to print the error to the console. I filed a karma [issue](https://github.com/karma-runner/karma/issues/2254) for this bug.
