### ISSUE TITLE
packages: {} - karma.conf doesn't apply.

### ISSUE THREAD

**Issue by nicklasb** [rolaveric/karma-systemjs#42]
I want to have a pure typescript app, therefore I want to load only .ts-files from the "test/"-folder.
So I added: 
```js
  packages: {
    'test': {
        defaultExtension: "ts"
    }
  },
```
...to the `systemjs`-section in karma.conf.
However, that doesn't work, it results in SystemJS wanting to load the .js-file anyway:
`Error: XHR error (404 Not Found) loading http://localhost:9876/base/test/test-main.mbe.spec.ts.js`

But, if I put the same setting in the jspm_config-file, the one i specify in `configFile`, it works, the .ts-file is loaded.

Have I misunderstood something? It would be nicer it the test config could be kept separate from the application config.

**Comment by rolaveric** [comment]
That's odd... You haven't misunderstood, the config specified in `systemjs.config` should override everything it finds in your application's config file.  And the adapter will only strip out '.js' from the end of a file path to try and get the module name - it certainly doesn't add anything.
I'll pull out and blow the dust off my Typescript example to see if I can track down the issue.

**Comment by nicklasb** [comment]
I just moved the declaration into the karma.conf.js, and this time it worked!
No idea why, but there have been significant upgrades to systemjs lately and I am running with `--edge`, so this has probably been solved elsewhere!

Closing!
