### ISSUE TITLE
Specifying testFileRegex does not work

### ISSUE THREAD

**Issue by spiralman** [rolaveric/karma-systemjs#43]
I'm trying to use the feature added in #33 but I always get an error:

```
Chrome 45.0.2454 (Mac OS X 10.10.4) ERROR
  TypeError: testFileRegexp.test is not a function
```

It seems that the value is not properly converted to a RegExp object when passed between the `index.js` code, running in node, and the `adapter.js` code, running in the browser.

I have tried both passing the value as a string (in which case it ends up as a string in browser land, but is never converted to a `RegExp` object), or as a RegExp in the Karma config file (in which case it gets passed as an opaque `Object` in browser land, which still does not have a `test` method).

I'd be happy to open a PR, but I'm not sure what approach you would want: should the value be specified as a string in the config file, and converted to a `new RegExp(config.testFileRegex)`? Or should it work to specify the regex as a `RegExp` object in the Karma config file? (I haven't looked at the runner/browser IPC to see how/if this is possible).

Here are the two different ways I've tried specifying the config:

```javascript
    systemjs: {
      configFile: 'system.config.js',
      testFileRegex: /test_.*\.js/
    },
    // ...
```

and

```javascript
    systemjs: {
      configFile: 'system.config.js',
      testFileRegex: 'test_.*\.js'
    },
    // ...
```

**Comment by rolaveric** [comment]
Hi @spiralman 

Well spotted.  The adapter.js code definitely expects a RegExp, but the unit tests show strings.  I'm pretty sure you can only pass strings from the framework down to the adapter.
However in the 0.8 branch (which I'm about to merge) the `testFileRegex` and `testFileSuffix` properties have been deprecated in favour of simply importing everything that has `{included: true}` (see #38), which should simplify things a lot for users.
