### ISSUE TITLE
test file matching not working

### ISSUE THREAD

**Issue by mikehaas763** [rolaveric/karma-systemjs#47]
I do not know how test file matching is set up.
I've listed my console log statements below.
Based on the filePath, should that file be matched as a test and run? It doesn't match the regex.

```
filePaths.hasOwnProperty(filePath)
true
importRegexp.test(filePath)
false
filePath
"/base/src/testingWorksSpec.js"
importRegexp
/^(?:\/base\/src\/(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^\/]*?Spec\.js)$/
```

**Comment by mikehaas763** [comment]
If you debug at lines 118 and 119 of framework.js I believe the problem is that Minimatch.makeRe() is not producing a valid regex.

**Comment by mikehaas763** [comment]
Made another discovery. Unfortunately I don't have the time to fully debug the framework to see what's happening but I noticed that I needed to add another `files` glob. Having just `dev/**/*Spec.js` did not work. I needed to also add `dev/*Spec.js` and then the test file was found and ran. Is this a bug or am I configured incorrectly?

**Comment by g0t4** [comment]
I'm having issues with paths like "tests/**/*.js" in my karam.conf.js with version 0.8.0's new loading via karma's files property.

**Comment by rolaveric** [comment]
I do remember seeing the problem with `src/**/*Spec.js` globs expecting at least 1 subfolder in the path.
But that appears to be the default behaviour for `minimatch`, which is the same library Karma uses for handling globs.
So I'm not sure if there's anything I can do about it.

**Comment by g0t4** [comment]
I just added the "base" folder to take care of it, so not a problem for me, maybe just add a note to the docs for this?
