### ISSUE TITLE
Breaking change in 0.8.0 not documented.

### ISSUE THREAD

**Issue by richburdon** [rolaveric/karma-systemjs#50]
I have the (simplified) config below. Moving from 0.7.2 to 0.8.0 no tests are found.

    module.exports = function(config) {
      config.set({
        "basePath": "src/main/javascript/",
        "systemjs": {
          "configFile": "config.js",
          "files": [
            "app/**/*.js",               // NO TESTS ARE FOUND IN 0.8.0
          ]
        },
        "files": [
          "testing/**/*.js"              // THIS IS NOW IGNORED IN 0.8.0
        ],
      });
    }

**Comment by rolaveric** [comment]
The discussion from this change is on #38
The README.md should describe how the configuration works, along with an addition to the Breaking Changes log at the bottom.
