### ISSUE TITLE
Files outside of basePath not imported

### ISSUE THREAD

**Issue by youngbob** [rolaveric/karma-systemjs#51]
karma-systemjs assumes that all test files are inside the basePath directory, and will be served from somewhere under '/base'. However, Karma will serve files included outside this directory under '/absolute'.

basePath: 'test'
files: ['foo/base.js', '../bar/abs.js']

Karma will serve:
/base/foo/base.js
/absolue/path/to/bar/abs.js

karma-systemjs will create a pattern that attempts to match '/base/path/to/bar/abs.js', which does not match, so the file will not be imported.

**Comment by rolaveric** [comment]
Merged #52 and published with v0.8.1
Thanks again!
