### ISSUE TITLE
Plugin not working on latest system.js release?

### ISSUE THREAD

**Issue by PWKad** [rolaveric/karma-systemjs#66]
We have a few skeleton projects which use TypeScript and karma-systemjs for running unit tests.  When updating to the latest release the karma tests all fail for the below error -

`
  Uncaught TypeError: Cannot read property 'replace' of null
  at /Users/pwalters/code/skeleton-navigation/skeleton-typescript/jspm_packages/system.js:4
`

This does not seem to happen when using karma-jspm plugin and since we are specifically defining karma-systemjs I wanted to see if this was known issue in the plugin or not.  Switching to an older version of the loader works fine.

**Comment by PWKad** [comment]
We would like to switch away from the karma-jspm library and convert all Aurelia users over to a single repository for testing which would probably help get this library some additional exposure as well as help us not maintain two versions of karma setups so let me know if we can help with anything.

Tracking - https://github.com/aurelia/skeleton-navigation/issues/276

**Comment by PWKad** [comment]
Confirmed this works on standard ES2016 so closing for now, assuming this is something to do with the TypeScript plugin or something, sorry for the false alarm.

**Comment by Roustalski** [comment]
So those of us using the typescript starter, what is the recommendation for unit tests?

**Comment by Roustalski** [comment]
Following the link above and then installing 0.19.6 rather than ^0.19.6 got me past the issue.

@see https://github.com/aurelia/skeleton-navigation/issues/276#issuecomment-179636198
