### ISSUE TITLE
Disable bundles for testing

### ISSUE THREAD

**Issue by muntact** [rolaveric/karma-systemjs#84]
I've got a jspm project which has bundles, however i don't want the bundles to be used for my tests, it would be nice to support disabling bundles in the same way that: https://github.com/Workiva/karma-jspm 
plugin does.

**Comment by rolaveric** [comment]
Thanks for the PR!
I'll create a 0.16.0 tag and release tonight once I get home.

**Comment by muntact** [comment]
@rolaveric 👍  awesome! you bet me to asking for a publish. Thanks

**Comment by rolaveric** [comment]
Published v0.16.0
