### ISSUE TITLE
SystemJS is not defined

### ISSUE THREAD

**Issue by ffflabs** [rolaveric/karma-systemjs#88]
system.js exports both System and SystemJS variables to the global namespace. However, it seems karma-systemjs only considers the first.

For this reason, when it tries to parse my `jspm.config.js` file, it complains that SystemJS is not defined, which is a pity, because even if I manually replace SystemJS with System in my config file, jspm will revert that change whenever I install a new dependency

**Comment by AdamWillden** [comment]
@amenadiel let me know if you find a way of working with this. I am up against the same issue.

**Comment by stravinskij** [comment]
I used Gulp, specifically gulp-replace, then used that as my configFile. 

```
gulp.task('replace-test', function() {
  gulp.src(['jspm.config.js'])
    .pipe(replace(/^SystemJS\.config/, 'System.config'))
    .pipe(gulp.dest('tstTmp/'));
});
```

**Comment by ffflabs** [comment]
@AdamWillden I moved on to [karma-jspm](https://github.com/computmaxer/karma-jspm)
