### ISSUE TITLE
SystemJS 0.20 no longer supports SystemJS.bundles

### ISSUE THREAD

**Issue by cexbrayat** [rolaveric/karma-systemjs#90]
Updating SystemJS to the latest release (0.20.0 has been released on January 24th) will break the tests that are using karma-systemjs with the error:

    Uncaught Error: Setting `SystemJS.bundles` directly is no longer supported. Use `SystemJS.config({ bundles: ... })`.

that I think `adapter.js` uses.

I tried to set up a PR, but it seems replacing it naively with `SystemJS.config({ bundles: [] })` breaks (unrelated?) unit tests.

**Comment by AdamWillden** [comment]
@cexbrayat thanks for noting the fix which was correct 👍 The failing tests were unrelated but needed updating to contain the now default empty bundles.

**Comment by AdamWillden** [comment]
...I meant to say see #92

**Comment by thomaschampagne** [comment]
Any updates? I'm getting this error too

**Comment by 82antu** [comment]
Same Issue Here....NOt on My MAchine,....but on CI runner on Gitlab just...
